"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "public/locales/en/*.json",
    "translation": "public/locales/%two_letters_code%/%original_file_name%",
    "languages_mapping": {
      "two_letters_code": {
        "fil": "fil",
        "te": "tl",
        "zh-CN": "cn",
      }
    }
  }
]
